version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my_network

  web:
    build: ./backend
    container_name: my-flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/flask_app
    depends_on:
      - mongodb
    environment:
      - PYTHONPATH=/flask_app
      - MONGO_URI=mongodb://root:example@mongodb:27017/
    networks:
      - my_network
    command: python backend/app.py --host=0.0.0.0 port=5000

networks:
  my_network:
    driver: bridge